Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracker.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BugTracker.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectRepo repo;

        public ProjectController(IProjectRepo repo)
        {
            this.repo = repo;
        }

        // GET: ProjectController
        public ActionResult Index()
        {
            var projects = repo.GetAll();
            
            return View(projects);
        }

        // GET: ProjectController/Details/5
        public ActionResult ViewProject(int id)
        {
            var project = repo.GetById(id);

            return View(project);
        }

        // GET: ProjectController/Create
        public IActionResult InsertProject()
        {
            var project = repo.AssignTicketsProp();
            return View(project);
        }

        // POST: ProjectController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        public IActionResult InsertProjectToDatabase(Project projectToInsert)
        {
            repo.Insert(projectToInsert);

            return RedirectToAction("Index");
        }

        // GET: ProjectController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProjectController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        public IActionResult UpdateProjectToDatabase(Project project)
        {
            repo.Update(project);

            return RedirectToAction("ViewProject", new { id = project.ProjectId });
        }

        public IActionResult DeleteProject(Project project)
        {
            repo.Delete(project);

            return RedirectToAction("Index");
        }

        public IActionResult Search(string searchTerm)
        {
            var search = repo.Search(searchTerm);

            return View(search);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UploadButtonClick(IFormFile files, Project project)
        {
            throw new NotImplementedException(); 
        }
    }
}

Controllers/TicketController.cs
using BugTracker.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using System;
using System.IO;

namespace BugTracker.Controllers
{
    public class TicketController : Controller
    {
        private readonly ITicketRepo repo;

        public TicketController(ITicketRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var tickets = repo.GetAll();

            return View(tickets);
        }

        public IActionResult ViewTicket(int id)
        {
            var ticket = repo.GetById(id);

            return View(ticket);
        }

        //is this even doing anything? Update: Yes--it's being called for the "Update Ticket" button in the ViewTicket
        public IActionResult UpdateTicket(int id)
        {
            //var projectList = GetProjects();
            //var ticket = new Ticket();
            //ticket.Projects = projectList;

            Ticket ticket = repo.GetById(id);
            ticket.Projects = repo.GetProjects();

            if (ticket == null)
            {
                return View("TicketNotFound");
            }

            return View(ticket);
        }
        
        public IActionResult UpdateTicketToDatabase(Ticket ticket)
        {
            
            repo.Update(ticket);

            return RedirectToAction("ViewTicket", new { id = ticket.TicketId });
        }

        public IActionResult InsertTicket()
        {
            var ticket = repo.AssignProjectsProp();
            return View(ticket);
        }

        public IActionResult InsertTicketToDatabase(Ticket ticketToInsert)
        {
            repo.Insert(ticketToInsert);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteTicket(Ticket ticket)
        {
            repo.Delete(ticket);

            return RedirectToAction("Index");
        }

        public IActionResult Search(string searchTerm)
        {
            var search = repo.Search(searchTerm);

            return View(search);
        }


        public IActionResult UploadButtonClick(IFormFile files, Ticket ticket)
        {
            if (files != null)
            {
                if (files.Length > 0)
                {
                    //Getting FileName
                    var fileName = Path.GetFileName(files.FileName);

                    //Assigning Unique Filename (Guid)
                    var myUniqueFileName = Convert.ToString(Guid.NewGuid());

                    //Getting file Extension
                    var fileExtension = Path.GetExtension(fileName);

                    // concatenating  FileName + FileExtension
                    var newFileName = String.Concat(myUniqueFileName, fileExtension);

                    // Combines two strings into a path.
                    var filepath =
            new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files")).Root + $@"{newFileName}";

                    using (FileStream fs = System.IO.File.Create(filepath))
                    {
                        files.CopyTo(fs);
                        fs.Flush();
                    }

                    ticket.File = "/files/" + newFileName;

                    repo.File(ticket);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BugTracker</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/datatables.min.css" />
    <link rel="stylesheet" href="~/css/cards-extended.min.css" />
    <link rel="stylesheet" href="~/css/datatables2.min.css" />
    <link rel="stylesheet" href="~/css/datatables-select.min.css" />
    <link rel="stylesheet" href="~/css/datatables-select2.min.css" />

    


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BugTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BugTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/js/popper.min.js"></script>
    <script type="text/javascript" src="~/js/mdb.min.js"></script>
    <script type="text/javascript" src="~/js/datatables.min.js"></script>
    <script type="text/javascript" src="~/js/cards-extended.min.js"></script>
    <script type="text/javascript" src="~/js/datatables2.min.js"></script>
    <script type="text/javascript" src="~/js/datatables-select.min.js"></script>
    <script type="text/javascript" src="~/js/datatables-select2.min.js"></script>

    @*@RenderSection("Scripts", required: false)*@
</body>
</html>